name: "Close Stale Issues"
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          days-before-stale: 30
          days-before-close: 7

          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security,wip'

          stale-issue-message: |
            This issue has been marked as stale due to 30 days of inactivity. It will be closed in 7 days if no further activity occurs. If this issue is still relevant, please leave a comment.
            
            ---
            
            由于 30 天内没有任何活动，此 Issue 已被标记为过期。如果在未来 7 天内没有进一步的活动，它将被自动关闭。如果问题仍然存在，请留言告知。

          close-issue-message: |
            This issue has been closed due to inactivity. Feel free to reopen it if you have more details.
            
            ---
            
            由于长时间未收到回复，此 Issue 已被自动关闭。如有需要，可以重新开启。